image: Visual Studio 2015
configuration:
- Debug
- DebugDLL
- DebugDLL_fixed
- Release
- ReleaseDLL
- ReleaseDLL_fixed

platform:
- Win32
- x64

build:
  project: win32\VS2015\opus.sln
  parallel: true
  verbosity: minimal

after_build:
- cmd: 7z a opus.zip win32\VS2015\%PLATFORM%\%CONFIGURATION%\opus.lib include\*.h

test_script:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%\win32\VS2015\%PLATFORM%\%CONFIGURATION%

    test_opus_api.exe

    test_opus_decode.exe

    test_opus_encode.exe

artifacts:
- path: opus.zip
