language: c

# We need at least Ubuntu 14.04 for the libopus dependency.
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - libogg-dev
      - libopus-dev

script:
  - ./autogen.sh
  - ./configure
  - make
  - make distcheck
